version: '3'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin_queue
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_queuing_new
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    depends_on:
      - db


volumes:
  postgres_data: